module Types
  class AccountType < GraphQL::Schema::Object
    field :id, ID, null: false
    field :name, String, null: true
    field :owner_id, Integer, null: true
    field :personal, Boolean, null: true
    field :created_at, GraphQL::Types::ISO8601DateTime, null: false
    field :updated_at, GraphQL::Types::ISO8601DateTime, null: false
    field :processor, String, null: true
    field :processor_id, String, null: true
    field :trial_ends_at, GraphQL::Types::ISO8601DateTime, null: true
    field :card_type, String, null: true
    field :card_last4, String, null: true
    field :card_exp_month, String, null: true
    field :card_exp_year, String, null: true
    field :extra_billing_info, String, null: true
    field :domain, String, null: true
    field :subdomain, String, null: true
    field :currency, String, null: true
    field :published, Boolean, null: true
    field :city, String, null: true
    field :country, String, null: true
    field :about, String, null: true
    field :stripe_publishable_key, String, null: true
    field :stripe_secret_key, String, null: true
    field :stripe_account_id, String, null: true
    field :pickup_address, String, null: true
    field :support_email, String, null: true
    field :support_phone, String, null: true
    field :open_time, GraphQL::Types::ISO8601DateTime, null: true
    field :close_time, GraphQL::Types::ISO8601DateTime, null: true
    field :pickup_instructions, String, null: true
    field :business_hours, String, null: true
    field :featured, Boolean, null: true
    field :monday, Boolean, null: true
    field :tuesday, Boolean, null: true
    field :wednesday, Boolean, null: true
    field :thursday, Boolean, null: true
    field :friday, Boolean, null: true
    field :saturday, Boolean, null: true
    field :sunday, Boolean, null: true
    field :listed, Boolean, null: true
    field :slot_interval_minutes, Integer, null: true
    field :slot_orders_max, Integer, null: true
    field :slot_order_items_max, Integer, null: true
    field :deleted_at, GraphQL::Types::ISO8601DateTime, null: true
    field :onboarding_completed_at, GraphQL::Types::ISO8601DateTime, null: true
    field :monday_cutoff_day, Integer, null: true
    field :monday_cutoff_time, GraphQL::Types::ISO8601DateTime, null: true
    field :tuesday_cutoff_day, Integer, null: true
    field :tuesday_cutoff_time, GraphQL::Types::ISO8601DateTime, null: true
    field :wednesday_cutoff_day, Integer, null: true
    field :wednesday_cutoff_time, GraphQL::Types::ISO8601DateTime, null: true
    field :thursday_cutoff_day, Integer, null: true
    field :thursday_cutoff_time, GraphQL::Types::ISO8601DateTime, null: true
    field :friday_cutoff_day, Integer, null: true
    field :friday_cutoff_time, GraphQL::Types::ISO8601DateTime, null: true
    field :saturday_cutoff_day, Integer, null: true
    field :saturday_cutoff_time, GraphQL::Types::ISO8601DateTime, null: true
    field :sunday_cutoff_day, Integer, null: true
    field :sunday_cutoff_time, GraphQL::Types::ISO8601DateTime, null: true
    field :delivery_fee, Float, null: true
    field :delivery_instructions, String, null: true
    field :deliveries_enabled, Boolean, null: true
    field :monday_delivery, Boolean, null: true
    field :tuesday_delivery, Boolean, null: true
    field :wednesday_delivery, Boolean, null: true
    field :thursday_delivery, Boolean, null: true
    field :friday_delivery, Boolean, null: true
    field :saturday_delivery, Boolean, null: true
    field :sunday_delivery, Boolean, null: true
    field :time_zone, String, null: true
    field :product_limit, Integer, null: true
    field :settings, String, null: true
    field :beta, Boolean, null: true
    field :last_stripe_charge, String, null: true
    field :theme_color, String, null: true
    field :hide_header_text, Boolean, null: true
    field :business_type, Integer, null: true
    field :buffer_minutes, Integer, null: true
    field :transaction_fee, Float, null: true
    field :legacy, Boolean, null: true
    field :menus_enabled, Boolean, null: true
    field :table_service_instructions, String, null: true
    field :latitude, Float, null: true
    field :longitude, Float, null: true
    field :coupon, String, null: true
    field :address, String, null: true
    field :directory_listing, Boolean, null: true
    field :custom_head_code, String, null: true
    field :custom_body_code, String, null: true
    field :stripe_express_account_id, String, null: true
    field :default_payment_method, Integer, null: true
    field :print_service_api_key, String, null: true
    field :printer_id, Integer, null: true
    field :printer_paper_size, String, null: true
    field :paper_width, Integer, null: true
    field :paper_height, Integer, null: true
    field :custom_paper_size, Boolean, null: true
    field :autoprint, Boolean, null: true
    field :limit_delivery_area, Boolean, null: true
    field :delivery_area, Float, null: true
    field :zoom_level, Integer, null: true
    field :dispatch_instructions, String, null: true
    field :aib_shared_secret, String, null: true
    field :aib_store_name, String, null: true
    field :fee_collection_frequency, Integer, null: true
    field :aib_payment_token, String, null: true
    field :aib_card_details, String, null: true
    field :aib_transaction_id, String, null: true
    field :setup_help_end_date, GraphQL::Types::ISO8601DateTime, null: true
    field :payment_policy, String, null: true
  end
end
